// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source interfaces.go -destination=./interfaces_mocks.go -package=client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockINodeshiftClient is a mock of INodeshiftClient interface.
type MockINodeshiftClient struct {
	ctrl     *gomock.Controller
	recorder *MockINodeshiftClientMockRecorder
	isgomock struct{}
}

// MockINodeshiftClientMockRecorder is the mock recorder for MockINodeshiftClient.
type MockINodeshiftClientMockRecorder struct {
	mock *MockINodeshiftClient
}

// NewMockINodeshiftClient creates a new mock instance.
func NewMockINodeshiftClient(ctrl *gomock.Controller) *MockINodeshiftClient {
	mock := &MockINodeshiftClient{ctrl: ctrl}
	mock.recorder = &MockINodeshiftClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINodeshiftClient) EXPECT() *MockINodeshiftClientMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockINodeshiftClient) CreateBucket(ctx context.Context, bucket *S3BucketConfig) (*S3BucketConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", ctx, bucket)
	ret0, _ := ret[0].(*S3BucketConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockINodeshiftClientMockRecorder) CreateBucket(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockINodeshiftClient)(nil).CreateBucket), ctx, bucket)
}

// CreateDeployment mocks base method.
func (m *MockINodeshiftClient) CreateDeployment(ctx context.Context, r *CreateDeploymentRequest) (*GetDeploymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeployment", ctx, r)
	ret0, _ := ret[0].(*GetDeploymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeployment indicates an expected call of CreateDeployment.
func (mr *MockINodeshiftClientMockRecorder) CreateDeployment(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeployment", reflect.TypeOf((*MockINodeshiftClient)(nil).CreateDeployment), ctx, r)
}

// CreateGPU mocks base method.
func (m *MockINodeshiftClient) CreateGPU(ctx context.Context, gpu *CreateGPURequest) (*GetGPUResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGPU", ctx, gpu)
	ret0, _ := ret[0].(*GetGPUResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGPU indicates an expected call of CreateGPU.
func (mr *MockINodeshiftClientMockRecorder) CreateGPU(ctx, gpu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGPU", reflect.TypeOf((*MockINodeshiftClient)(nil).CreateGPU), ctx, gpu)
}

// CreateLB mocks base method.
func (m *MockINodeshiftClient) CreateLB(ctx context.Context, lb *CreateLBRequest) (*GetLBResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLB", ctx, lb)
	ret0, _ := ret[0].(*GetLBResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLB indicates an expected call of CreateLB.
func (mr *MockINodeshiftClientMockRecorder) CreateLB(ctx, lb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLB", reflect.TypeOf((*MockINodeshiftClient)(nil).CreateLB), ctx, lb)
}

// CreateVPC mocks base method.
func (m *MockINodeshiftClient) CreateVPC(ctx context.Context, vpc *CreateVPCRequest) (*GetVPCResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVPC", ctx, vpc)
	ret0, _ := ret[0].(*GetVPCResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVPC indicates an expected call of CreateVPC.
func (mr *MockINodeshiftClientMockRecorder) CreateVPC(ctx, vpc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVPC", reflect.TypeOf((*MockINodeshiftClient)(nil).CreateVPC), ctx, vpc)
}

// DeleteBucket mocks base method.
func (m *MockINodeshiftClient) DeleteBucket(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBucket", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBucket indicates an expected call of DeleteBucket.
func (mr *MockINodeshiftClientMockRecorder) DeleteBucket(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBucket", reflect.TypeOf((*MockINodeshiftClient)(nil).DeleteBucket), ctx, key)
}

// DeleteDeployment mocks base method.
func (m *MockINodeshiftClient) DeleteDeployment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeployment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeployment indicates an expected call of DeleteDeployment.
func (mr *MockINodeshiftClientMockRecorder) DeleteDeployment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeployment", reflect.TypeOf((*MockINodeshiftClient)(nil).DeleteDeployment), ctx, id)
}

// DeleteGPU mocks base method.
func (m *MockINodeshiftClient) DeleteGPU(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGPU", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGPU indicates an expected call of DeleteGPU.
func (mr *MockINodeshiftClientMockRecorder) DeleteGPU(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGPU", reflect.TypeOf((*MockINodeshiftClient)(nil).DeleteGPU), ctx, id)
}

// DeleteLB mocks base method.
func (m *MockINodeshiftClient) DeleteLB(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLB", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLB indicates an expected call of DeleteLB.
func (mr *MockINodeshiftClientMockRecorder) DeleteLB(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLB", reflect.TypeOf((*MockINodeshiftClient)(nil).DeleteLB), ctx, uuid)
}

// DeleteVPC mocks base method.
func (m *MockINodeshiftClient) DeleteVPC(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVPC", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVPC indicates an expected call of DeleteVPC.
func (mr *MockINodeshiftClientMockRecorder) DeleteVPC(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVPC", reflect.TypeOf((*MockINodeshiftClient)(nil).DeleteVPC), ctx, id)
}

// DoSignedRequest mocks base method.
func (m *MockINodeshiftClient) DoSignedRequest(ctx context.Context, method, endpoint string, body io.ReadSeeker) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoSignedRequest", ctx, method, endpoint, body)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoSignedRequest indicates an expected call of DoSignedRequest.
func (mr *MockINodeshiftClientMockRecorder) DoSignedRequest(ctx, method, endpoint, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoSignedRequest", reflect.TypeOf((*MockINodeshiftClient)(nil).DoSignedRequest), ctx, method, endpoint, body)
}

// GetBucket mocks base method.
func (m *MockINodeshiftClient) GetBucket(ctx context.Context, key string) (*S3BucketConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucket", ctx, key)
	ret0, _ := ret[0].(*S3BucketConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucket indicates an expected call of GetBucket.
func (mr *MockINodeshiftClientMockRecorder) GetBucket(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucket", reflect.TypeOf((*MockINodeshiftClient)(nil).GetBucket), ctx, key)
}

// GetDeployment mocks base method.
func (m *MockINodeshiftClient) GetDeployment(ctx context.Context, id string) (*GetDeploymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployment", ctx, id)
	ret0, _ := ret[0].(*GetDeploymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployment indicates an expected call of GetDeployment.
func (mr *MockINodeshiftClientMockRecorder) GetDeployment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployment", reflect.TypeOf((*MockINodeshiftClient)(nil).GetDeployment), ctx, id)
}

// GetGPU mocks base method.
func (m *MockINodeshiftClient) GetGPU(ctx context.Context, id string) (*GetGPUResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPU", ctx, id)
	ret0, _ := ret[0].(*GetGPUResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPU indicates an expected call of GetGPU.
func (mr *MockINodeshiftClientMockRecorder) GetGPU(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPU", reflect.TypeOf((*MockINodeshiftClient)(nil).GetGPU), ctx, id)
}

// GetLB mocks base method.
func (m *MockINodeshiftClient) GetLB(ctx context.Context, uuid string) (*GetLBResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLB", ctx, uuid)
	ret0, _ := ret[0].(*GetLBResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLB indicates an expected call of GetLB.
func (mr *MockINodeshiftClientMockRecorder) GetLB(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLB", reflect.TypeOf((*MockINodeshiftClient)(nil).GetLB), ctx, uuid)
}

// GetVPC mocks base method.
func (m *MockINodeshiftClient) GetVPC(ctx context.Context, id string) (*GetVPCResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVPC", ctx, id)
	ret0, _ := ret[0].(*GetVPCResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVPC indicates an expected call of GetVPC.
func (mr *MockINodeshiftClientMockRecorder) GetVPC(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVPC", reflect.TypeOf((*MockINodeshiftClient)(nil).GetVPC), ctx, id)
}

// ListRegions mocks base method.
func (m *MockINodeshiftClient) ListRegions(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockINodeshiftClientMockRecorder) ListRegions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockINodeshiftClient)(nil).ListRegions), ctx)
}

// SetGlobalTransactionNote mocks base method.
func (m *MockINodeshiftClient) SetGlobalTransactionNote(note string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGlobalTransactionNote", note)
}

// SetGlobalTransactionNote indicates an expected call of SetGlobalTransactionNote.
func (mr *MockINodeshiftClientMockRecorder) SetGlobalTransactionNote(note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGlobalTransactionNote", reflect.TypeOf((*MockINodeshiftClient)(nil).SetGlobalTransactionNote), note)
}

// UpdateBucket mocks base method.
func (m *MockINodeshiftClient) UpdateBucket(ctx context.Context, bucket *S3BucketConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBucket", ctx, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBucket indicates an expected call of UpdateBucket.
func (mr *MockINodeshiftClientMockRecorder) UpdateBucket(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBucket", reflect.TypeOf((*MockINodeshiftClient)(nil).UpdateBucket), ctx, bucket)
}

// UpdateDeployment mocks base method.
func (m *MockINodeshiftClient) UpdateDeployment(ctx context.Context, id string, r *CreateDeploymentRequest) (*GetDeploymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeployment", ctx, id, r)
	ret0, _ := ret[0].(*GetDeploymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeployment indicates an expected call of UpdateDeployment.
func (mr *MockINodeshiftClientMockRecorder) UpdateDeployment(ctx, id, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeployment", reflect.TypeOf((*MockINodeshiftClient)(nil).UpdateDeployment), ctx, id, r)
}

// UpdateGPU mocks base method.
func (m *MockINodeshiftClient) UpdateGPU(ctx context.Context, id string, gpu *CreateGPURequest) (*GetGPUResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGPU", ctx, id, gpu)
	ret0, _ := ret[0].(*GetGPUResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGPU indicates an expected call of UpdateGPU.
func (mr *MockINodeshiftClientMockRecorder) UpdateGPU(ctx, id, gpu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGPU", reflect.TypeOf((*MockINodeshiftClient)(nil).UpdateGPU), ctx, id, gpu)
}

// UpdateLB mocks base method.
func (m *MockINodeshiftClient) UpdateLB(ctx context.Context, uuid string, lb *CreateLBRequest) (*GetLBResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLB", ctx, uuid, lb)
	ret0, _ := ret[0].(*GetLBResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLB indicates an expected call of UpdateLB.
func (mr *MockINodeshiftClientMockRecorder) UpdateLB(ctx, uuid, lb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLB", reflect.TypeOf((*MockINodeshiftClient)(nil).UpdateLB), ctx, uuid, lb)
}

// UpdateVPC mocks base method.
func (m *MockINodeshiftClient) UpdateVPC(ctx context.Context, id string, vpc *CreateVPCRequest) (*GetVPCResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVPC", ctx, id, vpc)
	ret0, _ := ret[0].(*GetVPCResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVPC indicates an expected call of UpdateVPC.
func (mr *MockINodeshiftClientMockRecorder) UpdateVPC(ctx, id, vpc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVPC", reflect.TypeOf((*MockINodeshiftClient)(nil).UpdateVPC), ctx, id, vpc)
}
