// Code generated by MockGen. DO NOT EDIT.
// Source: poller.go
//
// Generated by this command:
//
//	mockgen -source poller.go -destination=./poller_mocks.go -package=client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockrequester is a mock of requester interface.
type Mockrequester struct {
	ctrl     *gomock.Controller
	recorder *MockrequesterMockRecorder
	isgomock struct{}
}

// MockrequesterMockRecorder is the mock recorder for Mockrequester.
type MockrequesterMockRecorder struct {
	mock *Mockrequester
}

// NewMockrequester creates a new mock instance.
func NewMockrequester(ctrl *gomock.Controller) *Mockrequester {
	mock := &Mockrequester{ctrl: ctrl}
	mock.recorder = &MockrequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrequester) EXPECT() *MockrequesterMockRecorder {
	return m.recorder
}

// DoSignedRequest mocks base method.
func (m *Mockrequester) DoSignedRequest(ctx context.Context, method, endpoint string, body io.ReadSeeker) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoSignedRequest", ctx, method, endpoint, body)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoSignedRequest indicates an expected call of DoSignedRequest.
func (mr *MockrequesterMockRecorder) DoSignedRequest(ctx, method, endpoint, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoSignedRequest", reflect.TypeOf((*Mockrequester)(nil).DoSignedRequest), ctx, method, endpoint, body)
}
